project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('all_posts/',views.all_posts,name='all_posts'),
    path('post/<int:id>/',views.one_post,name='post'),
    path('create_post/',views.create_post,name='create_post'),
    path('<int:id>/edit/', views.edit_post, name='edit_post'),
]

project/job/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('', views.job_lists, name='job_list'),
    path('add_job/', views.add_job, name='add_job'),
    path('user_favourites/',views.user_favourite,name='user_favourites'),
    path('<str:slug>/', views.job_details, name='job_detail'),
    path('<str:slug>/like_or_unlike/',views.like_or_unlike,name='like_or_unlike'),


    # Functional Based View
    path('api/list', api.job_list_api, name='job_list_api'),
    path('api/list/<int:id>/', api.job_detail_api, name='job_detail_api'),

    # Class Based View
    path('api/jobs/', api.Job_List_Api.as_view(), name='Job_List_Api'),
    path('api/jobs/Add/', api.Job_List_Api1.as_view(), name='Job_List_Api1'),
    path('api/jobs/<int:id>/', api.Job_Detail_Api.as_view(), name='Job_Detail_Api')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls', namespace='job')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Post(models.Model):
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextField()
    img = models.ImageField(upload_to='media/')
    created_by = models.ForeignKey(User, null=True,blank=True,related_name='+', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

project/blog/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget)

    class Meta:
        model = Post
        fields = ['title', 'content', 'img']

project/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator
from django.contrib import messages


def all_posts(request):
    all_post = Post.objects.filter(active=True)
    paginator = Paginator(all_post,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'all_posts.html', {'all_post': page_obj})


def one_post(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'post_detail.html', {'post': post})


def create_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.created_by = request.user
            new_form.save()
            messages.success(request,'Post Created Successfully')
            return redirect('blog:all_posts')
        else:
            form = PostForm()
    return render(request, 'create_post.html', {'form': form})


def edit_post(request,id):
    post = get_object_or_404(Post,id=id)
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request,'Post Edited Successfully')
            return redirect('blog:all_posts')
        else:
            form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form})

project/blog/templates/all_posts.html
{% extends 'base_generic.html' %}

{% load static %}


{% block content1 %}
      <div class="messages"  style="width:80%; margin-left:100px;text-align:center; ">
        {% if messages %}
            <ul class="message" style=" color:white; list-style-type:none; padding:20px;">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                        <div class="alert alert-success" role="alert">
                        {{message}}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="jumbotron" style="width:100%; padding:40px;">
        <a class="btn btn-primary btn-lg" style="margin-left:305px;" href="{% url 'blog:create_post'%}" role="button"> Add New Post </a>
    </div>

    {% for post in all_post %}
        <div class="col-md-4" style="float:left;">
            <div class="card" style="margin-bottom:20px;">
                {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="..." >
                {% endif %}
                  <div class="card-body">
                    <h5 class="card-title" > {{post}} </h5>
                    <p class="card-text"> {{post.content|safe|truncatewords:40}} </p>
                    <a href="{% url 'blog:post' post.id %}" class="btn btn-primary"> Know More </a>
                  </div>
            </div>
        </div>
   {% endfor %}


<!-- Pagination -->
                {% if all_post.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                     {% if all_post.has_previous %}
                                        <li><a href="?page={{all_post.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                     {% endif %}

                                      {% for i in all_post.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                      {% endfor %}

                                         {% if all_post.has_next %}
                                                <li><a href="?page={{all_post.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                         {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                   {% endif %}
<!-- End Pagination -->

{% endblock %}

project/blog/templates/create_post.html
{% extends 'base_generic.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}

<div style="width:100%;">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" style="width:100%" value="Save Post">
    </form>
</div>

{% endblock %}

project/blog/templates/edit_post.html
{% extends 'base_generic.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}

<div style="width:100%">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" style="width:100%" value="Save Changes">
    </form>
</div>

{% endblock %}

project/blog/templates/post_detail.html
{% extends 'base_generic.html' %}


{% block content %}

{% if post.created_by == request.user %}
<div class="jumbotron" style="width:100%;padding:40px; margin-top:-100px;">
    <a class="btn btn-primary btn-lg" style="margin-left:320px;" href="{% url 'blog:edit_post' post.id %}" role="button"> Edit Post </a>
</div>
{% else %}

{% endif %}

            <div class="card" style="width:100%;" >
                  {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="..." width="200" height="200">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title"> {{post}} </h5>
                    <p class="card-text"> {{post.content|safe}} </p>

                  </div>
            </div>
{% endblock %}