project/accounts/urls.py
from django.urls import path
from . import views
from .import api

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),

    # Functional Based View
    path('api/profile/',api.profiles,name='api_profile'),
    path('api/profile/<int:id>/',api.profiles_id,name='api_profile_id'),

    # Class Based View
    path('api/profiles/', api.Profile_Api.as_view(), name='Profile_Api'),
    path('api/profiles/Add/', api.Profile_Api1.as_view(), name='Profile_Api1'),
    path('api/profiles/<int:id>/', api.Profile_Api2.as_view(), name='Profile_Api2')
]

project/job/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('', views.job_lists, name='job_list'),
    path('add_job/', views.add_job, name='add_job'),
    path('user_favourites/',views.user_favourite,name='user_favourites'),
    path('<str:slug>/', views.job_details, name='job_detail'),
    path('<str:slug>/like_or_unlike/',views.like_or_unlike,name='like_or_unlike'),


    # Functional Based View
    path('api/list', api.job_list_api, name='job_list_api'),
    path('api/list/<int:id>/', api.job_detail_api, name='job_detail_api'),

    # Class Based View
    path('api/jobs/', api.Job_List_Api.as_view(), name='Job_List_Api'),
    path('api/jobs/Add/', api.Job_List_Api1.as_view(), name='Job_List_Api1'),
    path('api/jobs/<int:id>/', api.Job_Detail_Api.as_view(), name='Job_Detail_Api')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls', namespace='job')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    objects = None
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Profile', null=True, blank=True)
    number_phone = models.CharField(max_length=15)
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '%s ' % self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class City(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

project/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'image', 'number_phone']

project/accounts/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import render, redirect
from .forms import SignUpForm, UserForm, ProfileForm
from .models import Profile
from django.urls import reverse


def signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('/accounts/profile')
        else:
            form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    my_profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'my_profile': my_profile})


def profile_edit(request):
    my_profile = Profile.objects.get(user=request.user)
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=my_profile)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=my_profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form1 = profile_form.save(commit=False)
            profile_form1.user = request.user
            profile_form1.save()
            return redirect(reverse('accounts:profile'))
        else:
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=my_profile)

    return render(request, 'accounts/profile_edit.html', {'user_form': user_form, 'profile_form': profile_form})

project/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block body %}


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3> Profile personal page </h3>
                             {% if my_profile.image %}
                                     <img src="{{my_profile.image.url}}" style="margin-left:340px; margin-top:-60px;" width="110" height="110" alt="profile image">
                             {% else %}
                                    <img src="{% static 'img/user/user.png' %}" style="margin-left:340px; margin-top:-60px;" width="110" height="110" alt="profile image">
                             {% endif %}
                        </div>
                        <div class="job_content">
                            <ul>
                                <li> Name : <span>{{my_profile}}</span></li>
                                <li> E-Mail : <span>{{my_profile.user.email}}</span></li>
                                <li> City : <span>{{my_profile.city}}</span></li>
                                <li> Phone-Number : <span> {{my_profile.number_phone}} </span></li>
                            </ul>
                            <br>
                             <p><a href="{% url 'accounts:profile_edit' %}"  class='boxed-btn3 w-100'> Edit Profile</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
</div>
{% endblock %}

project/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4> Edit Profile </h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form user_form %}
                            {% bootstrap_form profile_form %}
                            <button class="boxed-btn3 w-100" type="submit"> Save Changes </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}