project/job/urls.py
from django.urls import path
from . import views
from . import api

app_name = 'job'
urlpatterns = [
    path('', views.job_lists, name='job_list'),
    path('add_job/', views.add_job, name='add_job'),
    path('user_favourites/',views.user_favourite,name='user_favourites'),
    path('<str:slug>/', views.job_details, name='job_detail'),
    path('<str:slug>/like_or_unlike/',views.like_or_unlike,name='like_or_unlike'),


    # Functional Based View
    path('api/list', api.job_list_api, name='job_list_api'),
    path('api/list/<int:id>/', api.job_detail_api, name='job_detail_api'),

    # Class Based View
    path('api/jobs/', api.Job_List_Api.as_view(), name='Job_List_Api'),
    path('api/jobs/Add/', api.Job_List_Api1.as_view(), name='Job_List_Api1'),
    path('api/jobs/<int:id>/', api.Job_Detail_Api.as_view(), name='Job_Detail_Api')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls', namespace='job')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/job/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.utils.text import slugify
from django.contrib.auth.models import User


def image_upload(instance, filename):
    imagename, extension = filename.split(".")
    return 'jobs/%s.%s' % (instance.id, extension)


class Job(models.Model):
    objects = None
    JOB_TYPE = (
        ('Full Time', 'Full Time'),
        ('Part Time', 'Part Time')
    )
    owner = models.ForeignKey(User, related_name='job_owner', on_delete=models.CASCADE)
    like = models.ManyToManyField(User,blank=True)
    location = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=100, choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    facebook = models.CharField(max_length=500,null=True,blank=True)
    instagram = models.CharField(max_length=500,null=True,blank=True)
    google = models.CharField(max_length=500,null=True,blank=True)
    twitter = models.CharField(max_length=500,null=True,blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)

    class meta:
        verbose_name = _('Job')
        verbose_name_plural = _('Jobs')

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=25)

    class meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Apply(models.Model):
    job = models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now=True,null=True,blank=True)

    class Meta:
        verbose_name = _('Apply')
        verbose_name_plural = _('Applies')

    def __str__(self):
        return self.name

project/job/forms.py
from django import forms
from .models import Apply, Job


class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = ['name', 'email', 'website', 'cv', 'cover_letter']


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ('owner', 'slug')

project/job/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Job
from django.core.paginator import Paginator
from .forms import ApplyForm, JobForm
from django.contrib.auth.decorators import login_required
from .filters import JobFilter


def job_lists(request):
    job_list = Job.objects.all()
    my_filter = JobFilter(request.GET, queryset=job_list)
    job_list = my_filter.qs
    paginator = Paginator(job_list, 2)
    page_number = request.GET.get('page')
    job_list = paginator.get_page(page_number)
    return render(request, 'job_list.html', {'jobs': job_list, 'my_filter': my_filter})


@login_required(login_url='login')
def job_details(request, slug):
    job_detail = Job.objects.get(slug=slug)
    form = ApplyForm()
    if request.method == 'POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_detail
            my_form.save()
            return redirect(reverse('job:job_list'))
        else:
            form = ApplyForm()
    return render(request, 'job_detail.html', {'job_detail': job_detail, 'form': form})


def like_or_unlike(request,slug):
    job_detail = Job.objects.get(slug=slug)
    if request.user in job_detail.like.all():
        job_detail.like.remove(request.user)
    else:
        job_detail.like.add(request.user)
    return redirect(reverse('job:user_favourites'))


def user_favourite(request):
    user_favourites = Job.objects.filter(like=request.user)
    return render(request,'user_favourites.html',{'user_favourites':user_favourites})


@login_required(login_url='login')
def add_job(request):
    form = JobForm()
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.owner = request.user
            my_form.save()
            return redirect(reverse('job:job_list'))
        else:
            form = JobForm()
    return render(request, 'add_job.html', {'form': form})

project/job/templates/add_job.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/job/templates/job_detail.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block body %}


    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    {% if job_detail.image %}
                                          <img src="{{job_detail.image.url}}"  style="margin-top:-20px; margin-left:-20px;" width="90px" height="90px" alt="Image">
                                    {% else %}
                                          <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                                    {% endif %}
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job_detail}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job_detail.location}}  </p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job_detail.job_type}} </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    {% if request.user in job_detail.like.all %}
                                            <a class="heart" href="{% url 'job:like_or_unlike' job_detail.slug %}" style="padding-top:10px;"> <i class="ti-heart" style="background-color:#0f0; padding:8px;"></i> </a>
                                    {% else %}
                                            <a class="" href="{% url 'job:like_or_unlike' job_detail.slug %}" style="padding-top:10px"> <i class="ti-heart"></i> </a>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p> {{job_detail.description}} </p>
                        </div>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                          <button class="boxed-btn3 w-100" type="submit"> Apply Now </button>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on : <span>{{job_detail.published_at|date:'d - M - o'}}</span></li>
                                <li>Vacancy : <span>{{job_detail.vacancy}} Position</span></li>
                                <li>Salary : <span>{{job_detail.salary}}k - 120k/y</span></li>
                                <li>Location : <span>{{job_detail.location}}</span></li>
                                <li>Job Nature : <span> {{job_detail.job_type}} </span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
</div>
{% endblock %}

project/job/templates/job_list.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs|length}}+ Jobs Available</h3> <!-- {{jobs.count}} -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form my_filter.form %}
                                <button  class="boxed-btn3 w-100" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                                {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% if job.image %}
                                                  <img src="{{job.image.url}}"  style="margin-top:-20px; margin-left:-20px;" width="90px" height="90px" alt="Image">
                                            {% else %}
                                                <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                                            {% endif %}
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'job:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{job.location}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
<!--                                            <a class="heart_mark" href="#" style="padding:13px;"> <i class="fa fa-heart"></i> </a>-->
                                            <a href="{% url 'job:job_detail' job.slug %}" style="margin-left:130px;" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line : {{job.published_at|date:'d - M - o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        {% if jobs.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                     {% if jobs.has_previous %}
                                        <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                     {% endif %}

                                      {% for i in jobs.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                      {% endfor %}

                                         {% if jobs.has_next %}
                                                <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                         {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                   {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- job_listing_area_end  -->
{% endblock %}

project/job/templates/user_favourites.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}

{% for job in user_favourites %}
<div class="container" style="margin-bottom:140px;">
    <div class="row" style="margin-top:-120px;">
        <div class="col-lg-10">
            <div class="job_details_header">
                <div class="single_jobs white-bg d-flex justify-content-between" >
                    <div class="jobs_left d-flex align-items-center">
                        <div class="thumb">
                            {% if job.image %}
                                <img src="{{job.image.url}}"  style="margin-top:-20px; margin-left:-20px;" width="90px" height="90px" alt="Image">
                            {% else %}
                                <img src="{% static 'img/svg_icon/1.svg' %}" alt="">
                            {% endif %}
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'job:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.location}}  </p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.job_type}} </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
{% endfor %}

{% endblock %}